branch-defaults:
  master:
    environment: notebook-api-5
    group_suffix: null
global:
  application_name: notebook-api-5
  branch: null
  default_ec2_keyname: '1'
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
